language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
deploy:
  provider: releases
  api_key:
    secure: 
  file: target/helloci-1.0-SNAPSHOT.jar
  on:
    repo: giorgos1987/helloci
    all_branches: true
    tags: true
