language: java
jdk:
- oraclejdk8
#- oraclejdk7
#- openjdk7

before_deploy:
  - "mvn -DskipTests package"
  - export FOO=$(ls target/foo-version-*.jar)

deploy:
  provider: releases
  api_key: 531ec678a481842ab826959e240920451b155cba
  file: target/helloci-1.0-SNAPSHOT.jar
  on:
    repo: giorgos1987/helloci
    all_branches: true
    tags: true
