language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
deploy:
  provider: releases
  api_key: ad31ee851e80d7205507e9d16a75544e2d4d51dc
  file: target/helloci-1.0-SNAPSHOT.jar
  on:
    repo: giorgos1987/helloci
    all_branches: true
    tags: true
